### ISSUE TITLE
Use R version from `renv.lock` in Rhino app CI

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/rhino#342]

**Comment by vibalre** [comment]
The `R` version in `renv.lock` should be the same as the `R_VERSION` specified in `rhino-test.yml`.

For example, `.github/workflows/rhino-test.yml` can be configured as 

```
name: Rhino Test
on: push
jobs:
  main:
    name: Run linters and tests
    runs-on: ubuntu-20.04
    env:
      R_VERSION: '4.1.0'
``` 

But `renv.lock` can be configured as 

```
"R": {
    "Version": "4.1.1",
    "Repositories": [
      {
        "Name": "RSPM",
        "URL": "https://packagemanager.rstudio.com/all/latest"
      }
    ]
  }
```

We want the `rhino-test.yml` to use `R_VERSION: '4.1.1'`.
